apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
  namespace: web
rules:
- apiGroups: [""]
  resources: ["services", "pods", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-rolebinding
  namespace: web
subjects:
- kind: ServiceAccount
  name: workflow-sa
  namespace: default
roleRef:
  kind: Role
  name: workflow-role
  apiGroup: rbac.authorization.k8s.io 
